### ISSUE TITLE
Clicking on  scoreboard crashes the application

### ISSUE THREAD

**Issue by meirtsvi** [meirtsvi/WazeWP7#30]
"Method not found: NOPH_EmbeddedBrowser_EmbeddedBrowserShow Syscalls."

   at CibylCallTable.fcall(Int32 address, Int32 sp, Int32 a0, Int32 a1, Int32 a2, Int32 a3)
   at Cibyl64.roadmap_browser_show_ssd_1055e5c(Int32 A_0, Int32 A_1, Int32 A_2, Int32 A_3, Int32 A_4)
   at Cibyl64.roadmap_browser_show_extended_1056090(Int32 A_0, Int32 A_1, Int32 A_2, Int32 A_3, Int32 A_4)
   at Cibyl64.roadmap_browser_show_10560dc(Int32 A_0, Int32 A_1, Int32 A_2, Int32 A_3, Int32 A_4)
   at Cibyl56.roadmap_scoreboard_104bb18(Int32 A_0, Int32 A_1, Int32 A_2, Int32 A_3, Int32 A_4)
   at CibylCallTable.fcall(Int32 address, Int32 sp, Int32 a0, Int32 a1, Int32 a2, Int32 a3)
   at UIWorker.runEventQueue(Boolean forever)
   at UIWorker.run()
   at System.Threading.ThreadHelper.ThreadStartHelper(ThreadHelper t)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStartHelper()

**Comment by meirtsvi** [comment]
Resolved
